# Generated by Django 4.2.4 on 2023-08-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(default=11, max_length=11, unique=True, verbose_name='phonenumber'),
            preserve_default=False,
        ),
    ]
