# Generated by Django 4.2.4 on 2023-08-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=111, max_length=11, unique=True, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
