# Generated by Django 4.2.4 on 2023-08-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='users_customuser_age_range',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('age__range', (10, 70))), name='users_customuser_age_range'),
        ),
    ]
